### PR TITLE
fix: rotation of touch and tablet not working

### LINKED ISSUE #13: [Bug] Not working with special category
Running iio-hyprland spits out following into stdout:
```
ok
special category's first value must be the key. Key for <device> is <name>
special category's first value must be the key. Key for <device> is <name>
special category's first value must be the key. Key for <device> is <name>
```
I got the screen rotation working by adding a fixed monitor in `hyprland.conf`, but touch and stylus do not work.
It seems that `hyprctl` changed how to set ids.

This is running on a:
`ASUS ROG Flow X13 GV301RE`

In KDE rotation of screen and digitizers work correctly.

EDIT:
seems like the keyword changed.
To set rotation on touch and tablet the following commands will do the trick:
```
hyprctl keyword input:touchdevice:transform $d
hyprctl keyword input:tablet:transform $d
```

Maybe it's also a good idea to run it in the `batch` command mode of `hyprctl`?

### PR DESCRIPTION
**Pull request by short-circuit**
fixes #13

Please let me know if there should be any other changes.

### CODE REVIEW

**Comment by tofeeh** [comment]
Dude, you have a hardcoded solution for your laptop, and it broke iio-hyprland for everyone else.
previous solution work, and after this new pull it stops
here is from my hyprctl devices
```
Tablets:
	Tablet at 62d849584670:
		wacom-hid-52cd-pen


Touch:
	Touch Device at 62d8490bb920:
		wacom-hid-52cd-finger

```
can you tell me how this should be rooted according to the update you have made?, why don't you just use OR and add your device name patter to the awk list?

**Comment by short-circuit** [comment]
Hey sorry if this caused you issues. The pull request is still open though, so no merge has been done and it is not available on the master repo. You can still normally use the master branch without using my pull request.

I tried this on multiple convertibles (thinkpad x13, asus x13, asus zenbook flip) with latest hyprland from git and worked on all devices so far.

Can you tell me your hyprland version so I can test it with the specific version and what device that is?
Also, if possible, post the output log so I can see what it is doing? I can try changing the implementation based on your input so that it's backwards compatible.

The `keyword` implementation should rotate all devices that are recognized as touch and tablet. The previous implementation did not work for the devices I use.

Thank you

**Comment by Mahgozar** [comment]
this worked for me 
thank you for the fix

**Comment by tofeeh** [comment]
It was my skill issue. I connected the hyprland update with this commit, I tested it, and it works, thank you, but now I have another issue
image
the screen rotates, but not all elements rotate.

**Comment by Yusuf-Duran** [comment]
this does not seem to work for me, I still get the same error
```
./iio-hyprland 
ok
special category's first value must be the key. Key for <device> is <name>
special category's first value must be the key. Key for <device> is <name>
special category's first value must be the key. Key for <device> is <name>
special category's first value must be the key. Key for <device> is <name>
```

Maybe I set it up wrong but here is the information about my system:
Device : Surface Pro 7
Distro: NixOs

**Comment by Yusuf-Duran** [comment]
nvm seems to work now (I'n not fully sure what I changed but just ignore my previous comment)

**Comment by sondresj** [comment]
This actually fixed it for me too, seems like hyprland ignores device<device name> config but respects input:touchdevice

**Comment by jacekpoz** [comment]
works on Dell Latitude 7320 Detachable, nixos

**Comment by JeanSchoeller** [comment]
Merged.

**Pull request merged**
